direction: right

vars: {
  d2-config: {
    layout-engine: elk
  }
}

# D2の構文をより単純に保ちつつ、自己射をオフセットして表示
a: mind {
  style.fill: lightyellow
  style.stroke-width: 2
  style.stroke: black
}

a -> a: 仕事終わったんよ {
  style.stroke-width: 2
  style.animated: true
  style.fill: "#f5f5f5"
}

a -> a: もうこんな時間じゃのう {
  style.stroke-width: 2
  style.animated: true
  style.fill: "#f5f5f5"
}

a -> a: 家に帰ろう思うたんよ {
  style.stroke-width: 2
  style.animated: true
  style.fill: "#f5f5f5"
}

a -> a: お腹減ったのう {
  style.stroke-width: 2
  style.animated: true
  style.fill: "#f5f5f5"
}

a -> a: そろそろ寝ようかのう {
  style.stroke-width: 2
  style.animated: true
  style.fill: "#f5f5f5"
}
