api_server: api_server(ReservationService.create)

front -> api_server: カレンダーで予約作成(即時利用)
api_server -> ocpp_server: 即時利用の予約作成
ocpp_server -> charger: 充電開始指令OCPPService.start(this.ocppMessageClient.request)

charger -> ocpp_server: プラグイン(s-p) {
  style.stroke: red
}
charger <- ocpp_server: 充電開始指令 {
  style.stroke: red
}
